# Change prefix keybinding from C-b to `
unbind C-b
set-option -g prefix '`'

# Change split keybindings from % and " to | and - respectively
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# Change quit keybinding from & to q
unbind &
bind q killp

set -g mouse on # Enables mouse features (e.g scrolling, text selection + copy/paste, etc.)

bind -n S-Left swap-window -t -1\; select-window -t -1
bind -n S-Right swap-window -t +1\; select-window -t +1

# Vim keybindings for pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Link tmux clipboard to system clipboard
set -s set-clipboard on
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
