set -g mouse on # Enables mouse features (e.g scrolling, text selection + copy/paste, etc.)

bind -n S-Left swap-window -t -1\; select-window -t -1
bind -n S-Right swap-window -t +1\; select-window -t +1

# Link tmux clipboard to system clipboard
set -s set-clipboard on
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
